# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_85EIYlTr2s03-xeVtFTo3L59OOai8J8
"""

x=5
print(f"變數x的值是:{x}")
print(f"變數x的記憶體地址是:{id(x)}")